# Generated by Django 2.2.2 on 2019-08-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190805_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(default=123123, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
