# Generated by Django 2.2.4 on 2019-08-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscription_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='interval',
            field=models.CharField(choices=[('annual', 'annual'), ('quarterly', 'quarterly'), ('monthly', 'monthly')], max_length=10),
        ),
    ]
